/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

/**
 *
 * @author fabioh
 */
public class frmTelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form frmTelaInicial
     */
    public frmTelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMorador = new javax.swing.JButton();
        btnCorretor = new javax.swing.JButton();
        btnEntregador = new javax.swing.JButton();
        btnVisitante = new javax.swing.JButton();
        btnPrestador = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1Condominio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMorador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMorador.setText("Morador");
        btnMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoradorActionPerformed(evt);
            }
        });

        btnCorretor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCorretor.setText("Corretor");
        btnCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorretorActionPerformed(evt);
            }
        });

        btnEntregador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEntregador.setText("Entregador");
        btnEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregadorActionPerformed(evt);
            }
        });

        btnVisitante.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVisitante.setText("Visitante");
        btnVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitanteActionPerformed(evt);
            }
        });

        btnPrestador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPrestador.setText("Prestador");
        btnPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestadorActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1Condominio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1Condominio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Condominio.setText("Condominio Tulipa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1Condominio, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1Condominio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btnVisitante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEntregador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCorretor)
                            .addComponent(btnPrestador, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(32, 32, 32))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCorretor, btnEntregador, btnMorador, btnPrestador, btnVisitante});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorretor))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntregador)
                    .addComponent(btnPrestador))
                .addGap(30, 30, 30)
                .addComponent(btnVisitante)
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCorretor, btnEntregador, btnMorador, btnPrestador, btnVisitante});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorretorActionPerformed
       frmCorretor corretor = new frmCorretor();
       corretor.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnCorretorActionPerformed

    private void btnMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoradorActionPerformed
       frmMorador morador = new frmMorador();
       morador.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnMoradorActionPerformed

    private void btnEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregadorActionPerformed
       frmEntregador entregador = new frmEntregador();
       entregador.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEntregadorActionPerformed

    private void btnPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestadorActionPerformed
        frmPrestador prestador = new frmPrestador();
        prestador.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPrestadorActionPerformed

    private void btnVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitanteActionPerformed
       frmVisitante visitante = new frmVisitante();
       visitante.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnVisitanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCorretor;
    private javax.swing.JButton btnEntregador;
    private javax.swing.JButton btnMorador;
    private javax.swing.JButton btnPrestador;
    private javax.swing.JButton btnVisitante;
    private javax.swing.JLabel jLabel1Condominio;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
