/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.VisitanteDAO;
import br.com.projeto.model.Utilitarios;
import br.com.projeto.model.Visitante;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabioh
 */
public class frmVisitante extends javax.swing.JFrame {

    //metodo listar na tabela
    public void listar() {
        VisitanteDAO dao = new VisitanteDAO();
        List<Visitante> lista = dao.listarVisitante();
        DefaultTableModel dados = (DefaultTableModel) tabelaVisitante.getModel();
        dados.setNumRows(0);
        for (Visitante c : lista) {
            dados.addRow(new Object[]{
                c.getId_visitante(),
                c.getNome(),
                c.getCpf(),
                c.getAp_visita()

            });
        }
    }

    /**
     * Creates new form frmVisitante
     */
    public frmVisitante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painel_principal = new javax.swing.JTabbedPane();
        painel_dados = new javax.swing.JPanel();
        Codigo = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelApvisita = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtApvisita = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        btnSalvar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnExcluir1 = new javax.swing.JButton();
        btnbusca = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Nome1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVisitante = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro Visitante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        painel_principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel_principalMouseClicked(evt);
            }
        });

        painel_dados.setBackground(new java.awt.Color(255, 255, 255));

        Codigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Codigo.setText("Código:");

        Nome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nome.setText("Nome:");

        jLabelCpf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCpf.setText("Cpf:");

        jLabelApvisita.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelApvisita.setText("Ap. Visita:");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtApvisita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnSalvar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalvar1.setText("Cadastrar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        btnEditar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        btnExcluir1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnExcluir1.setText("Excluir");
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });

        btnbusca.setText("Pesquisar");
        btnbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_dadosLayout = new javax.swing.GroupLayout(painel_dados);
        painel_dados.setLayout(painel_dadosLayout);
        painel_dadosLayout.setHorizontalGroup(
            painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_dadosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo)
                    .addGroup(painel_dadosLayout.createSequentialGroup()
                        .addGroup(painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApvisita)
                            .addComponent(jLabelCpf)
                            .addComponent(Nome))
                        .addGap(44, 44, 44)
                        .addGroup(painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtApvisita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnbusca)))
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_dadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar1)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir1)
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar)
                .addGap(85, 85, 85))
        );

        painel_dadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditar1, btnExcluir1, btnSalvar1, jButtonVoltar});

        painel_dadosLayout.setVerticalGroup(
            painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_dadosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbusca))
                .addGap(18, 18, 18)
                .addGroup(painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApvisita)
                    .addComponent(txtApvisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(painel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar1)
                    .addComponent(btnExcluir1)
                    .addComponent(jButtonVoltar))
                .addContainerGap())
        );

        painel_dadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditar1, btnExcluir1, btnSalvar1, jButtonVoltar});

        painel_principal.addTab("Dados Pessoais", painel_dados);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Nome1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nome1.setText("Nome:");
        Nome1.setToolTipText("");

        txtPesquisa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tabelaVisitante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cpf", "Ap.Visita"
            }
        ));
        tabelaVisitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVisitanteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVisitante);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Nome1)
                        .addGap(36, 36, 36)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnPesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome1)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        painel_principal.addTab("Consulta de Visitante", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_principal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painel_principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        //botao salvar

        Visitante obj = new Visitante();
        obj.setNome(txtNome.getText());
        obj.setCpf(txtCpf.getText());
        obj.setAp_visita(txtApvisita.getText());

        VisitanteDAO dao = new VisitanteDAO();
        dao.cadastrarVisitante(obj);
        new Utilitarios().LimpaTela(painel_dados);
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        //botao editar

        Visitante obj = new Visitante();
        obj.setNome(txtNome.getText());
        obj.setCpf(txtCpf.getText());
        obj.setAp_visita(txtApvisita.getText());

        obj.setId_visitante(Integer.parseInt(txtCodigo.getText()));

        VisitanteDAO dao = new VisitanteDAO();
        dao.alterarVisitante(obj);
        new Utilitarios().LimpaTela(painel_dados);
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        //botao excluir
        Visitante obj = new Visitante();

        obj.setId_visitante(Integer.parseInt(txtCodigo.getText()));

        VisitanteDAO dao = new VisitanteDAO();
        dao.excluirVisitante(obj);
        new Utilitarios().LimpaTela(painel_dados);
    }//GEN-LAST:event_btnExcluir1ActionPerformed

    private void btnbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaActionPerformed
        // botao busca por nome
        String nome = txtNome.getText();
        Visitante obj = new Visitante();
        VisitanteDAO dao = new VisitanteDAO();

        obj = dao.consultaPorNome(nome);

        if (obj.getNome() != null) {
            //exibe dados
            txtCodigo.setText(String.valueOf(obj.getId_visitante()));
            txtNome.setText(obj.getNome());
            txtCpf.setText(obj.getCpf());
            txtApvisita.setText(obj.getAp_visita());
        } else {
            JOptionPane.showMessageDialog(null, "Visitante nao encontrado");
        }

    }//GEN-LAST:event_btnbuscaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        frmTelaInicial telainicial = new frmTelaInicial();
        telainicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        // botao pesquisar
        String nome = "%" + txtPesquisa.getText() + "%";
        VisitanteDAO dao = new VisitanteDAO();
        List<Visitante> lista = dao.buscaVisitantePorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaVisitante.getModel();
        dados.setNumRows(0);
        for (Visitante c : lista) {
            dados.addRow(new Object[]{
                c.getId_visitante(),
                c.getNome(),
                c.getCpf(),
                c.getAp_visita()

            });
        }

    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // botao pesquisar
        String nome = "%" + txtPesquisa.getText() + "%";
        VisitanteDAO dao = new VisitanteDAO();
        List<Visitante> lista = dao.buscaVisitantePorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaVisitante.getModel();
        dados.setNumRows(0);
        for (Visitante c : lista) {
            dados.addRow(new Object[]{
                c.getId_visitante(),
                c.getNome(),
                c.getCpf(),
                c.getAp_visita()

            });
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tabelaVisitanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVisitanteMouseClicked
        // pega os dados
        painel_principal.setSelectedIndex(0);
        txtCodigo.setText(tabelaVisitante.getValueAt(tabelaVisitante.getSelectedRow(), 0).toString());
        txtNome.setText(tabelaVisitante.getValueAt(tabelaVisitante.getSelectedRow(), 1).toString());
        txtCpf.setText(tabelaVisitante.getValueAt(tabelaVisitante.getSelectedRow(), 2).toString());
        txtApvisita.setText(tabelaVisitante.getValueAt(tabelaVisitante.getSelectedRow(), 3).toString());

    }//GEN-LAST:event_tabelaVisitanteMouseClicked

    private void painel_principalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_principalMouseClicked

    }//GEN-LAST:event_painel_principalMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // carrega lista
        listar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVisitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Nome1;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JButton btnbusca;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApvisita;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painel_dados;
    private javax.swing.JTabbedPane painel_principal;
    private javax.swing.JTable tabelaVisitante;
    private javax.swing.JTextField txtApvisita;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
